# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

operator = input("Enter an operator (+ - * /): ")
num1 = float(input("Enter the 1st number: "))
num2 = float(input("Enter the 2nd number: "))

if operator == "+":
  result = num1 + num2
  print(round(result, 2))
elif operator == "-":
  result = num1 - num2
  print(round(result, 2))
elif operator == "*":
  result = num1 * num2
  print(round(result, 2))
elif operator == "/":
  result = num1 / num2
  print(round(result, 2))
else:
  print(f"{operator} is not a valid operator")